#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

FROM python:3-alpine

# Enable if using Proxy, and building manually
#ENV DEBIAN_FRONTEND=noninteractive
#ENV http_proxy="http://127.0.0.1:9080" HTTP_PROXY="http://127.0.0.1:9080" https_proxy="http://127.0.0.1:9080" HTTPS_PROXY="http://127.0.0.1:9080"

# Or your actual UID, GID on Linux if not the default 1000
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
# Avoid warnings by switching to noninteractive
# But don't use ENV, coz ENV persists in the Containers too
#ARG DEBIAN_FRONTEND=noninteractive

# Configure apt and install packages
RUN apk update && \
    apk add --no-cache git sudo build-base zsh && \
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended" && \
    sed -i 's/plugins=(git)/plugins=(gitfast\ alias-finder\ battery\ colorize\ common-aliases\ cp\ extract\ fancy-ctrl-z\ jsontools\ python\ pyenv\ urltools)/g' ~/.zshrc
#    addgroup -g 1000 ${USERNAME} && \
#    adduser -s /bin/sh -S -u 1000 ${USERNAME} ${USERNAME} && \
#    touch /home/${USERNAME}/.zshrc && \
#    echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
#    su -c 'sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"' - ${USERNAME} && \
#    su -c "sed -i 's/plugins=(git)/plugins=(gitfast\ alias-finder\ battery\ colorize\ common-aliases\ cp\ extract\ fancy-ctrl-z\ jsontools\ python\ pyenv\ urltools)/g' /home/${USERNAME}/.zshrc" - ${USERNAME}
# Switch back to dialog for any ad-hoc use of apt-get
#ENV DEBIAN_FRONTEND=

#ENTRYPOINT [ "/bin/zsh" ]
